import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

import { api } from "../../utils/api";

const PollPage: NextPage = () => {
  const router = useRouter();
  const pollId = router.query.pollId as string;
  const [selectedAnswer, setSelectedAnswer] = useState<string | undefined>();

  const pollResponse = api.poll.getPoll.useQuery(
    {
      pollId,
    },
    {
      enabled: !!pollId,
    }
  );

  console.log(pollResponse);

  const poll = pollResponse.data;

  function handlePollSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (!selectedAnswer) return;
    console.log("submitted");
  }

  return (
    <>
      <Head>
        <title>Answer a Poll</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        {pollResponse.isLoading ? (
          <>Loading...</>
        ) : (
          <section className="flex flex-col gap-4">
            <h1 className="text-4xl">{poll?.prompt}</h1>
            <form className="flex flex-col gap-4" onSubmit={handlePollSubmit}>
              {poll?.answers.map((answer) => {
                const inputId = `input-${answer.id}`;
                return (
                  <fieldset key={answer.id} className="flex gap-2">
                    <input
                      id={inputId}
                      type="radio"
                      checked={selectedAnswer === answer.id}
                      onChange={() => setSelectedAnswer(answer.id)}
                    />
                    <label htmlFor={inputId}>{answer.text}</label>
                  </fieldset>
                );
              })}
              <button className="bg-blue-400 px-3 py-2 text-white hover:bg-blue-500">
                Submit
              </button>
            </form>
          </section>
        )}
      </main>
    </>
  );
};

export default PollPage;
